# Generated by Django 5.2.5 on 2025-08-28 14:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Тип операции',
                'verbose_name_plural': 'Типы операций',
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_type_name'), models.UniqueConstraint(fields=('slug',), name='unique_type_slug')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('operation_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='categories', to='dds.operationtype')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_status_name'), models.UniqueConstraint(fields=('slug',), name='unique_status_slug')],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subcategories', to='dds.category')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма в рублях', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='records', to='dds.category')),
                ('operation_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='records', to='dds.operationtype')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='records', to='dds.status')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='records', to='dds.subcategory')),
            ],
            options={
                'verbose_name': 'Запись ДДС',
                'verbose_name_plural': 'Записи ДДС',
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_category_name'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_category_slug'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_subcategory_name'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_subcategory_slug'),
        ),
        migrations.AddIndex(
            model_name='cashflow',
            index=models.Index(fields=['created_at'], name='created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflow',
            index=models.Index(fields=['status'], name='status_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflow',
            index=models.Index(fields=['operation_type'], name='operation_type_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflow',
            index=models.Index(fields=['category'], name='category_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflow',
            index=models.Index(fields=['subcategory'], name='subcategory_idx'),
        ),
    ]
